FROM node:20-alpine

WORKDIR /app/src/frontend

COPY src/frontend/package*.json ./
RUN npm install

COPY src/frontend ./

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
