services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      FRONTEND_URL: "http://localhost:3000"
      AUTH_ENABLED: "${AUTH_ENABLED:-false}"
      SENTRY_ENABLED: "${SENTRY_ENABLED:-false}"
    volumes:
      - ./:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
      VITE_AUTH_ENABLED: "${VITE_AUTH_ENABLED:-false}"
      VITE_FEATURE_ANNOTATE_PAGE: "${VITE_FEATURE_ANNOTATE_PAGE:-false}"
      VITE_FEATURE_SIDEBAR_PROJECTS: "${VITE_FEATURE_SIDEBAR_PROJECTS:-true}"
      VITE_FEATURE_SIDEBAR_IMPORT: "${VITE_FEATURE_SIDEBAR_IMPORT:-false}"
      VITE_FEATURE_SIDEBAR_AI: "${VITE_FEATURE_SIDEBAR_AI:-false}"
      VITE_FEATURE_SIDEBAR_FILTER: "${VITE_FEATURE_SIDEBAR_FILTER:-false}"
      VITE_FEATURE_SIDEBAR_STATS: "${VITE_FEATURE_SIDEBAR_STATS:-false}"
      VITE_FEATURE_SIDEBAR_MODEL_ANALYSIS: "${VITE_FEATURE_SIDEBAR_MODEL_ANALYSIS:-false}"
      VITE_FEATURE_SIDEBAR_EXPORT: "${VITE_FEATURE_SIDEBAR_EXPORT:-true}"
      VITE_FEATURE_SIDEBAR_PROJECT_SETTINGS: "${VITE_FEATURE_SIDEBAR_PROJECT_SETTINGS:-false}"
      VITE_FEATURE_PAGE_SUBSCRIPTION: "${VITE_FEATURE_PAGE_SUBSCRIPTION:-false}"
      VITE_FEATURE_PAGE_ORGANISATION: "${VITE_FEATURE_PAGE_ORGANISATION:-false}"
      VITE_FEATURE_PAGE_SETTINGS: "${VITE_FEATURE_PAGE_SETTINGS:-false}"
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/app/src/frontend
      - /app/src/frontend/node_modules
