site_name: Depict-AI Documentation
site_description: technical documentation for Depict-AI , Image data tool for computer vision
site_author: Edouard Geze, Tangi Migot
repo_url: https://github.com/Depict-CV/Depict-AI

nav:
  - Home: index.md
  - About: about.md
  - Developers Guide:
      - sentry tutorial: sentry.md

theme:
  name: readthedocs
  language: en

plugins:
  - search
  - include_dir_to_nav # Include all files from a directory into the navigation
  - include-markdown:
      encoding: utf-8
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0
      recursive: true
