site_name: Depict AI
site_description: Image data tool for computer vision
theme:
  name: material
plugins:
  - search
  - include_dir_to_nav # Include all files from a directory into the navigation
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0
      recursive: true
