[project]
name = "Depict-AI"
version = "0.1.0"
description = '''
image data tool for computer vision from raw images to model training/fine-tuning.
tasks: data visualization, annotation, dataset management, cleaning.
cv tasks: classification, object detection, segmentation. images and videos.
'''
authors = [
    {name = "Edouard Geze",email = "edouard.geze@hotmail.fr"}
]
license = {text = "\"AGPL-3.0\""}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4,<3.0.0",
    "fastapi[standard] (>=0.125.0,<0.126.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "sqlmodel (>=0.0.27,<0.0.28)",
    "torch==2.9.1+cpu",
    "pillow (>=12.0.0,<13.0.0)",
    "torchvision==0.24.1+cpu",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "python-dotenv (>=1.0.0,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "minio (>=7.2.0,<8.0.0)",
    "huggingface-hub (>=1.4.1,<2.0.0)",
    "transformers (>=5.1.0,<6.0.0)",
]

[tool.ruff]
line-length = 120
extend-select = ["I"]

[tool.poetry]
packages = [
    {include = "backend", from = "src"},
    {include = "frontend", from = "src"},
    {include = "ml", from = "src"}
]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
torch = {version = "2.9.1+cpu", source = "pytorch-cpu"}
torchvision = {version = "0.24.1+cpu", source = "pytorch-cpu"}

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.1,<10.0.0)",
    "ruff (>=0.14.7,<0.15.0)",
    "mkdocs (>=1.6.0,<2.0.0)",
    "mkdocs-material (>=9.5.0,<10.0.0)",
    "pymdown-extensions (>=10.0.0,<11.0.0)",
    "mkdocs-include-markdown-plugin (>=7.0.0,<8.0.0)",
    "pre-commit (>=4.5.0,<5.0.0)"
]
