from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlmodel import Session

from src.backend.api.deps import get_session
from src.backend.db.tables import Project

router = APIRouter(prefix="/notifications", tags=["notifications"])


class NotificationCreate(BaseModel):
    image_id: int
    project_id: int
    type: str = "annotation_change"
    status: str = "pending"
    image_location: Optional[str] = None


class NotificationUpdate(BaseModel):
    status: str


class NotificationResponse(BaseModel):
    id: int
    image_id: int
    project_id: int
    project_name: str
    type: str
    status: str
    image_location: Optional[str] = None
    created_at: datetime
    created_by: int

    class Config:
        from_attributes = True


###############
#    create   #
###############
@router.post("/", response_model=dict)
def create_notification(notification: NotificationCreate, db: Session = Depends(get_session)):
    """Create a new notification/change request"""
    try:
        # Get project to include project name
        project = db.get(Project, notification.project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # In a real implementation, you'd have a Notification table
        # For now, we'll return the created notification data
        # You should create a Notification table in your database schema

        return {
            "id": 1,  # This should be generated by the database
            "image_id": notification.image_id,
            "project_id": notification.project_id,
            "project_name": project.name,
            "type": notification.type,
            "status": notification.status,
            "image_location": notification.image_location,
            "created_at": datetime.now().isoformat(),
            "message": "Notification created successfully",
        }
    except Exception as error:
        raise HTTPException(status_code=500, detail=str(error))


###############
#    read     #
###############
@router.get("/project/{project_id}")
def get_project_notifications(project_id: int, status: Optional[str] = Query(None), db: Session = Depends(get_session)):
    """Get all notifications for a project"""
    try:
        # Get project
        project = db.get(Project, project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # In a real implementation, query the Notification table
        # For now, return empty list
        # SELECT * FROM notifications WHERE project_id = ? AND (status = ? OR ? IS NULL)

        return []
    except Exception as error:
        raise HTTPException(status_code=500, detail=str(error))


@router.get("/user")
def get_user_notifications(db: Session = Depends(get_session)):
    """Get all notifications for projects the user is a member of"""
    try:
        # In a real implementation, query notifications for all user's projects
        # For now, return empty list

        return []
    except Exception as error:
        raise HTTPException(status_code=500, detail=str(error))


###############
#   update    #
###############
@router.put("/{notification_id}")
def update_notification(notification_id: int, update_data: NotificationUpdate, db: Session = Depends(get_session)):
    """Update a notification's status"""
    try:
        # In a real implementation, update the Notification table
        # UPDATE notifications SET status = ? WHERE id = ?

        return {"id": notification_id, "status": update_data.status, "message": "Notification updated successfully"}
    except Exception:
        raise HTTPException(status_code=404, detail="Notification not found")


###############
#   delete    #
###############
@router.delete("/{notification_id}")
def delete_notification(notification_id: int, db: Session = Depends(get_session)):
    """Delete a notification"""
    try:
        # In a real implementation, delete from the Notification table
        # DELETE FROM notifications WHERE id = ?

        return {"message": f"Notification {notification_id} deleted successfully"}
    except Exception:
        raise HTTPException(status_code=404, detail="Notification not found")
